app/Http/routes.php
<?php

// Auth
Route::group([
	'prefix' => 'auth',
	'namespace' => 'Auth'
], function() {
	// Login
	Route::get('/login', [
		'as' => 'auth.login.get',
		'uses' => 'AuthController@getLogin'
	]);
	Route::post('/login', [
		'as' => 'auth.login.post',
		'uses' => 'AuthController@postLogin'
	]);

	// Logout
	Route::get('/logout', [
		'as' => 'auth.logout',
		'uses' => 'AuthController@getLogout'
	]);

	// Register
	Route::get('/register', [
		'as' => 'auth.register.get',
		'uses' => 'AuthController@getRegister'
	]);

	Route::post('/register', [
		'as' => 'auth.register.post',
		'uses' => 'AuthController@postRegister'
	]);
});

// Home
Route::get('/', [
	'as' => 'home',
	'uses' => 'PageController@showHome',
]);

// Favorites
Route::get('favorites', [
	'as' => 'favorites.index',
	'uses' => 'FavoriteListController@index',
	'middleware' => 'auth'
]);

// Shopping Cart
Route::get('/shopping-cart', [
	'as' => 'shopping-cart.index',
	'uses' => 'ShoppingCartController@index'
]);

// Payment
Route::get('payment/choose-method', [
	'as' => 'payment.choose-method',
	'uses' => 'PaymentController@chooseMethod',
]);

Route::post('payment/save-method', [
	'as' => 'payment.save-method',
	'uses' => 'PaymentController@saveMethod',
]);

// Order
Route::get('/orders/confirm', [
	'as' => 'orders.confirm.get',
	'uses' => 'OrderController@getConfirm',
]);

Route::post('/orders/confirm', [
	'as' => 'orders.confirm.post',
	'uses' => 'OrderController@postConfirm',
]);

Route::get('orders/thank-you', [
	'as' => 'orders.thank-you',
	'uses' => 'OrderController@showThankYou'
]);

// API
Route::group([
	'prefix' => 'api/v1',
	'namespace' => 'Api'
], function() {
	// Favorite list
	Route::post('favorite-list/store', [
		'as' => 'api.v1.favorite-list.store',
		'uses' => 'FavoriteListController@store'
	]);

	// Search
	Route::post('search', [
		'as' => 'api.v1.search.query',
		'uses' => 'SearchController@query'
	]);

	// Game Review Resource
	Route::resource('reviews', 'GameReviewController', [
		'only' => [
			'show',
			'store'
		]
	]);

	// Order
	Route::resource('orders', 'OrderController', [
		'only' => [
			'show',
		]
	]);

	// Order Rules
	Route::get('/order-rules/order/{orderId}', [
		'as' => 'order-rules.show-by-order-id',
		'uses' => 'OrderRuleController@showByOrderId'
	]);

	Route::post('/order-rules/{orderRuleId}/set-retrieved', [
		'as' => 'order-rules.set-retrieved',
		'uses' => 'OrderRuleController@setRetrieved'
	]);

	// Shopping Cart
	Route::post('/shopping-cart/add-game', [
		'as' => 'api.v1.shopping-cart.add-game',
		'uses' => 'ShoppingCartController@addGame'
	]);

	Route::post('/shopping-cart/update-quantity/{gameId}', [
		'as' => 'api.v1.shopping-cart.updateQuantity',
		'uses' => 'ShoppingCartController@updateQuantity'
	]);

	Route::delete('/shopping-cart/remove-game/{gameId}', [
		'as' => 'api.v1.shopping-cart.remove-game',
		'uses' => 'ShoppingCartController@removeGame'
	]);

	Route::get('/shopping-cart/get-contents', [
		'as' => 'api.v1.shopping-cart.get-contents',
		'uses' => 'ShoppingCartController@getContents'
	]);

	// Game Screenshot
	Route::get('/screenshots/{gameId}', [
		'as' => 'api.v1.screenshots.get-by-game-id',
		'uses' => 'GameScreenshotController@getByGameId'
	]);

	// Game Resource
	Route::resource('games', 'GameController', [
		'only' => [
			'show'
		]
	]);

	Route::get('games/discount/{id}', [
		'as' => 'api.v1.games.discount',
		'uses' => 'GameController@discountedPrice'
	]);

	Route::get('games/check-if-released/{id}', [
		'as' => 'api.v1.games.check-if-released',
		'uses' => 'GameController@checkIfReleased'
	]);
});

// Admin
Route::group([
	'prefix' => 'admin',
	'namespace' => 'Admin',
	'middleware' => 'auth'
], function() {
	// Root
	Route::get('/', function() {
		return redirect()->route('admin.dashboard.index');
	});

	// Dashboard
	Route::get('dashboard', [
		'as' => 'admin.dashboard.index',
		'uses' => 'DashboardController@index',
		'middleware' => 'shop.assistant'
	]);

	Route::get('pre-orders', [
		'as' => 'admin.pre-orders',
		'uses' => 'PreOrderController@index'
	]);

	// Games Resource
	Route::resource('games', 'GameController', [
		'except' => ['show'],
		'middleware' => 'admin'
	]);

	// Publishers Resource
	Route::resource('publishers', 'PublisherController', [
		'except' => ['show'],
		'middleware' => 'admin'
	]);

	// Platform Resource
	Route::resource('platforms', 'PlatformController', [
		'except' => ['show'],
		'middleware' => 'admin'
	]);

	// Manufacturer Resource
	Route::resource('manufacturers', 'ManufacturerController', [
		'except' => ['show'],
	]);

	// User Resource
	Route::resource('users', 'UserController', [
		'except' => ['show'],
		'middleware' => 'admin'
	]);

	// Order Resource
	Route::resource('orders', 'OrderController', [
		'except' => ['show'],
		'middleware' => 'admin'
	]);

	Route::get('day-overview', [
		'as' => 'admin.day-overview',
		'uses' => 'OverviewController@dayOverview'
	]);
});

// Single Platform
Route::get('/{platformSlug}', [
	'as' => 'platform.show-by-slug',
	'uses' => 'PlatformController@showBySlug',
]);

// Single Game
Route::get('/{platformSlug}/{gameSlug}', [
	'as' => 'game.show-by-slug',
	'uses' => 'GameController@showBySlug',
]);

app/Publisher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Publisher extends Model {
	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'publishers';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'slug',
		'description',
		'logo_path',
	];
}

app/Http/Controllers/Admin/PublisherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Publisher;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PublisherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $publishers = Publisher::all();

        return view('admin.publishers.index', compact('publishers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.publishers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // TODO: ADD VALIDATION
        Publisher::create([
            'name' => $request->input('name'),
            'slug' => $request->input('slug'),
            'description' => $request->input('description'),
            'logo_path' => $request->input('logo-path'),
        ]);

        // TODO: ADD FLASH MESSAGE
        return redirect()->route('admin.publishers.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $publisher = Publisher::find($id);

        return view('admin.publishers.edit', compact('publisher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // TODO: ADD VALIDATION
        $publisher = Publisher::find($id);

        $publisher->update([
            'name' => $request->input('name'),
            'slug' => $request->input('slug'),
            'description' => $request->input('description'),
            'logo_path' => $request->input('logo-path'),
        ]);

        // TODO: ADD FLASH MESSAGE
        return redirect()->route('admin.publishers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Publisher::destroy($id);

        // TODO: ADD FLASH MESSAGE
    }
}

resources/views/admin/publishers/create.blade.php
@extends('admin.layouts.default')

@section('content')
    <h1>New Publisher</h1>
    <form action="{{ route('admin.publishers.store') }}" method="POST">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label for="title">Name</label>
            <input class="form-control" name="name" id="name" type="text" placeholder="Enter name"/>
        </div>

        <div class="form-group">
            <label for="slug">Slug</label>
            <input class="form-control" name="slug" id="slug" type="text" placeholder="Enter slug"/>
        </div>

        <div class="form-group">
            <label for="logo-path">Url to logo</label>
            <input class="form-control" name="logo-path" id="logo-path" type="text" placeholder="Enter url to logo"/>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description" placeholder="Enter description" rows="3"></textarea>
        </div>

        <input type="submit" class="btn btn-primary pull-right" value="Save Publisher"/>
    </form>
    <br/><br/>
@stop

resources/views/admin/publishers/edit.blade.php
@extends('admin.layouts.default')

@section('content')
    <h1>Update Publisher</h1>
    <form action="{{ route('admin.publishers.update', ['publishers' => $publisher->id]) }}" method="POST">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label for="title">Name</label>
            <input class="form-control" name="name" id="name" type="text" placeholder="Enter name" value="{{ $publisher->name }}"/>
        </div>

        <div class="form-group">
            <label for="slug">Slug</label>
            <input class="form-control" name="slug" id="slug" type="text" placeholder="Enter slug" value="{{ $publisher->slug }}"/>
        </div>

        <div class="form-group">
            <label for="logo-path">Url to logo</label>
            <input class="form-control" name="logo-path" id="logo-path" type="text" placeholder="Enter url to logo" value="{{ $publisher->logo_path }}"/>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" name="description" id="description" placeholder="Enter description" rows="3">{{ $publisher->description }}</textarea>
        </div>

        <input type="submit" class="btn btn-primary pull-right" value="Save Publisher"/>
    </form>
    <br/><br/>
@stop

resources/views/admin/publishers/index.blade.php
@extends('admin.layouts.default')

@section('content')
    <a href="{{ route('admin.publishers.create') }}" class="btn btn-primary pull-right">Add new publisher</a>
    <h1>Publishers</h1>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        @foreach($publishers as $publisher)
            <tr id="publisher-{{ $publisher->id }}">
                <td>{{ $publisher->id }}</td>
                <td>{{ $publisher->name }}</td>
                <td><a href="{{ route('admin.publishers.edit', ['publishers' => $publisher->id]) }}"><i class="fa fa-pencil"></i></a></td>
                <td><a href="#" onClick="deletePublisher({{ $publisher->id }})"><i class="fa fa-trash"></i></a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@stop

@section('script')
    <script>
        function deletePublisher(id) {
            if (confirm('Are you sure you want to delete this game?')) {
                $.ajax({
                    url: '/admin/publishers/' + id,
                    method: 'DELETE',
                    success: function(response) {
                        console.log(response);
                        $('#publisher-'+id).remove();
                    }
                });
            }
        }
    </script>
@stop
@stop